name: context_menus
description: A package to show context menus on right-click or long-press.
version: 0.1.0+6
homepage: https://github.com/gskinnerTeam/flutter-context-menu

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
